packages:
  - apps/*
  - packages/*

catalog:
  "@libsql/client": ^0.17.0
  "@types/node": 24.10.4
  typescript: ^5.9.3
  zod: ^4.3.6

catalogs:
  better-auth:
    better-auth: ^1.4.18
  cloudflare:
    "@cloudflare/vite-plugin": ^1.23.0
    "@cloudflare/workers-types": ^4.20260203.0
    wrangler: ^4.62.0
  dicebear:
    "@dicebear/collection": ^9.3.1
    "@dicebear/core": ^9.3.1
  drizzle:
    drizzle-kit: ^0.31.8
    drizzle-orm: ^0.45.1
  effect:
    "@effect-atom/atom-react": ^0.5.0
    "@effect/experimental": ^0.58.0
    "@effect/language-service": ^0.73.0
    "@effect/platform": ^0.94.3
    "@effect/rpc": ^0.73.0
    "@effect/sql": ^0.49.0
    "@effect/sql-d1": ^0.47.0
    "@effect/sql-drizzle": ^0.48.0
    effect: ^3.19.16
  react:
    "@types/react": ^19.2.11
    "@types/react-dom": ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4
  tailwind:
    "@tailwindcss/vite": ^4.1.18
    tailwind-merge: ^3.4.0
    tailwindcss: ^4.1.18
    tw-animate-css: ^1.4.0
  tanstack:
    "@tanstack/react-form": ^1.28.0
    "@tanstack/react-router": ^1.158.0
    "@tanstack/react-start": ^1.158.0
    "@tanstack/react-table": ^8.21.3
  vite:
    "@vitejs/plugin-react": ^5.1.3
    "@vitest/browser-playwright": ^4.0.18
    vite: ^7.3.1
    vitest: ^4.0.18
    vitest-browser-react: ^2.0.5
